### ISSUE TITLE
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor

### ISSUE THREAD

**Issue by toretto460** [wnameless/docker-oracle-xe-11g#7]
I can't connect to the container via Toad (jdbc).

**error**:
```
java.sql.SQLException: Listener refused the connection with the following error:
ORA-12505, TNS:listener does not currently know of SID given in connect descriptor
```

**connection string**: `jdbc:oracle:thin:@localhost:49161:xe`

Anyone has some suggestion?

**Comment by kakawait** [comment]
Same here since few weeks

**Comment by wnameless** [comment]
Here is a new version released. Please try it again.

**Comment by kakawait** [comment]
Thank you I will try that as soon as possible

**Comment by yannxia** [comment]
Today, i use it also tell me ORA-12541: TNS:no listner.  how to fix it?

**Comment by matheustardivo** [comment]
Try using this: `jdbc:oracle:thin:@localhost:49161/xe`

**Comment by MattFriedman** [comment]
I have had the same problem; no ability to connect from a remote machine. 

I fixed it manually by doing the following: 

```
set ORACLE_SID=<YOUR_SID>
sqlplus "/as sysdba"
alter system disable restricted session;
```
See: https://community.oracle.com/thread/1100776?tstart=0

Once I did that I seem to be able to connect from a remote machine.

Otherwise, I get things like connection refused and TNS:no listener

It would be great if the image came with remote listening allowed by default.

Any suggestions on how I might update the image to fix this?

**Comment by wnameless** [comment]
It's a security issue and I am not sure if this is right to make this behaviour as default.
Some users may not want their db to be connected remotely.

**Comment by MattFriedman** [comment]
@wnameless I see, that's valid and fair. Perhaps an env var that could alter the behaviour? That would make it explicit if someone wants to enable remote but the default would still be local only. Just a thought.  Thanks very much for this image.

**Comment by wnameless** [comment]
The ORACLE_ALLOW_REMOTE option has been added.
Please see the detail in the README.md.
