### ISSUE TITLE
Forgotten users when Shutdown and startup, OS

### ISSUE THREAD

**Issue by AlexSnake11** [wnameless/docker-oracle-xe-11g#99]
Hi, 

I was create an user `CREATE USER usuario IDENTIFIED BY contrasenia`, and works, but when restart os and try connect whit the user and pwd don't work. Can u help me?

Best regards.

**Comment by MarkLeMerise** [comment]
@AlexSnake11 You need to give the Docker container access to an external volume, otherwise _all_ data will be lost on restart. [There is an already an issue with solutions to this problem](https://github.com/wnameless/docker-oracle-xe-11g/issues/64). However, I ran this variation for my use case and it has persisted data across restarts:
```bash
docker run --name oracle11g -d -p 49161:1521 -v ~/Documents/oracle11g-data/:/u01/app/oracle/oradata/oracle11g-data/  --restart=always wnameless/oracle-xe-11g
```

The local path can be whatever you want on your machine (given Docker can read/write there), I just happened to pick `~/Documents/oracle11g-data/`.

**Comment by mikperic** [comment]
Hi @AlexSnake11  @MarkLeMerise 
I have the same issue, but mounting /u01/app/oracle/oradata/oracle11g-data/ doesn't solve it for me. Why would we mount /u01/app/oracle/oradata/oracle11g-data/ ? It is not official folder where Oracle persist data. Quick search on Google returned no official info about this folder.

**Comment by MarkLeMerise** [comment]
@mikperic Haven't used this image in nearly two years, but [this comment from #64 worked for me at the time](https://github.com/wnameless/docker-oracle-xe-11g/issues/64#issuecomment-328147589). I would suggest looking in the Oracle docs, or even `ssh`'ing into the image and looking around its directory structure. Lastly, there may be other Oracle XE images (maybe even an official one) in Docker hub.
